# Generated by Django 4.2.2 on 2023-07-11 17:09

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='images',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1', '3/2', '16/9'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, height_field='800', pixel_densities=[1, 2], upload_to='produtos', width_field='800'),
        ),
    ]
